arb-dir: l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
preferred-supported-locales: [en]
nullable-getter: false
untranslated-messages-file: missing_translations.txt
