name: tudo_app
description: A simple to-do app
version: 2.0.0
homepage: https://github.com/cachapa/tudo
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  hive: ^2.2.3
  http: ^0.13.5
  web_socket_channel: ^2.3.0

  provider: ^6.0.5
  rxdart: ^0.27.7
  sqlite_crdt: ^0.0.9+1
  # Required for Android and iOS because UPSERTs are only supported on very recent OS versions
  sqlite3_flutter_libs: ^0.5.13

  clipboard: ^0.1.3
  device_info_plus: ^8.1.0
  flutter_barcode_scanner: ^2.0.0
  implicitly_animated_reorderable_list:
    git:
      url: https://github.com/storyark-app/implicitly_animated_reorderable_list.git
      ref: flutter_beta

  in_app_update: ^4.0.1
  package_info_plus: ^3.0.3
  platform_info: ^3.2.0
  path_provider: ^2.0.14
  qr_flutter: ^4.0.0
  share_plus: ^6.3.1
  uni_links: ^0.5.1
  uuid: ^3.0.7
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
