name: tudo_server
description: Server counterpart to the tudo app
version: 1.0.0
homepage: https://github.com/cachapa/tudo

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.2
  http: ^0.13.5
  rxdart: ^0.27.7
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  shelf_web_socket: ^1.0.3
  sqlite_crdt: ^0.0.6
  web_socket_channel: ^2.3.0
  version: ^3.0.2

dev_dependencies:
  lints: any
  test: any
