name: Quality Gate (server)

on:
  push:
    branches:
      - '**'

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1

      - name: Verify code formatting
        run: dart format --output none --set-exit-if-changed .

      - name: Get dependencies
        run: dart pub get

      - name: Static code analysis
        run: dart analyze --fatal-infos

#      - name: Run tests
#        run: pub run test
