name: Quality Gate (app)

on:
  push:
    branches:
      - '**'

defaults:
  run:
    working-directory: app

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
#        with:
#          channel: 'beta'

      - name: Verify code formatting
        run: dart format --output none --set-exit-if-changed .

      - name: Load config
        run: echo "${{ secrets.CONFIG }}" > lib/config.dart

      - name: Static code analysis
        run: flutter analyze

#      - name: Run tests
#        run: flutter test
